version: '3.3'
services:
  todo-rest-api:
    image: solvedshared/todo-rest-api-mysql:1.0.0.RELEASE
    ports:
      - "8080:8080"
    restart: always
    environment:
      RDS_HOSTNAME: jj974-dbserver-name.database.windows.net
      RDS_PORT: 1433
      RDS_DB_NAME: jj974-database
      RDS_USERNAME: jj974-dbadmin@jj974-dbserver-name
      RDS_PASSWORD: TrudieIsLief12
